### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Nathan2055** [jlord/hasinternet#3]
There isn't a license provided for this.

**Comment by jlord** [comment]
It's BSD. It's in `package.json` but I'll add the license file, too. 

https://github.com/jlord/hasinternet/blob/master/package.json#L14

**Comment by Nathan2055** [comment]
Ah, didn't see that. Sorry for any trouble!

**Comment by jlord** [comment]
No worries! I usually have the file in there, but missed this one somehow. Thanks!
